### ISSUE TITLE
Syntax highlighting of first 'from' is wrong

### ISSUE THREAD

**Issue by stevenreddie** [dabbott/javascript-playgrounds#21]
Hi, I noticed in Chrome (Mac; 57.0.2987.133) that http://dabbott.github.io/react-native-web-player/ and also the official Tutorial render the first 'from' below in black, whereas the second is light-blue:

```
import React, { Component } from 'react'
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native'

```
I can provide a screenshot if useful.

Thanks,
Steven

**Comment by dabbott** [comment]
Thanks! This is due to the CodeMirror JS mode not recognizing syntax like `import A, { B } from 'c'`. I'm using an outdated fork of CodeMirror where I hackily added better ES6 and JSX support. Probably updating CodeMirror will solve this (presumably it's fully compatible with ES6 now)... although might make JSX support worse. Will just have to try it and see.

**Comment by dabbott** [comment]
I'm probably just not going to fix this, since it's pretty minor.
