### ISSUE TITLE
Alert.alert("") is not working

### ISSUE THREAD

**Issue by merbin2012** [dabbott/javascript-playgrounds#35]
In this web player not support "Alert.alert" method
[Check the error](https://cdn.rawgit.com/dabbott/react-native-web-player/gh-v2.0.0-alpha.3/index.html#platform=ios&code=import%20React%2C%20%7B%20Component%20%7D%20from%20'react'%3B%0Aimport%20%7B%20Button%2CAlert%20%7D%20from%20'react-native'%3B%0A%0Aexport%20default%20class%20PizzaTranslator%20extends%20Component%20%7B%0A%0Atest()%0A%7B%0A%20%20Alert('You%20tapped%20the%20button!')%3B%0A%20%20%0A%7D%0A%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CButton%0A%20%20onPress%3D%7B()%20%3D%3E%20%7B%0A%20%20%20%20Alert.alert('You%20tapped%20the%20button!')%3B%0A%20%20%7D%7D%0A%20%20title%3D%22Press%20Me%22%0A%2F%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D)

`import React, { Component } from 'react';
import { Button,Alert } from 'react-native';

export default class PizzaTranslator extends Component {

test()
{
  Alert('You tapped the button!');
  
}

  render() {
    return (
      <Button
  onPress={() => {
    Alert.alert('You tapped the button!');
  }}
  title="Press Me"
/>
    );
  }
}`

**Comment by dabbott** [comment]
Sorry I missed this. It looks like `Alert.alert` isn't supported by `react-native-web`, probably because it would be hard to support all the parameters in a meaningful way.

https://github.com/necolas/react-native-web/blob/36dacb2052efdab2a28655773dc76934157d9134/packages/react-native-web/src/exports/Alert/index.js
