### ISSUE TITLE
Support 3rd party components (without changing the bundle)

### ISSUE THREAD

**Issue by nbclark** [dabbott/javascript-playgrounds#8]
Would be nice to be able to use the iframe method to include 3rd party components in the sandbox. I've thrown together a working solution for it here if you want to take a look:

https://github.com/dabbott/react-native-web-player/compare/master...doubledutch:master

**Comment by dabbott** [comment]
This is great! I'm kinda swamped with stuff atm but your implementation looks solid. Feel free to make a PR. I've been meaning to get around to this.  Also solves: https://github.com/dabbott/react-native-web-player/issues/6

**Comment by dabbott** [comment]
I merged https://github.com/dabbott/react-native-web-player/pull/9.

After playing with it a little, I'm wondering if we should expect a commonjs format for 3rd party dependencies?

I first tried loading [this gist](https://gist.githubusercontent.com/dabbott/6d269634a006e167552f25a61f8680b4/raw/4527a4ab2c7be457b164395f763b86bc07b3e370/test.js), before realizing I'd probably have to [attach it to Window](https://gist.githubusercontent.com/dabbott/6d269634a006e167552f25a61f8680b4/raw/ea85b628b66758a0a599226a457b82b19d479c50/test.js), which [works](http://localhost:8080/#vendorComponents=%5B%5B%22test%22%2C%20%22Test%22%2C%20%22https%3A%2F%2Frawgit.com%2Fdabbott%2F6d269634a006e167552f25a61f8680b4%2Fraw%2Fea85b628b66758a0a599226a457b82b19d479c50%2Ftest.js%22%5D%5D&code=import%20React%2C%20%7B%20Component%2C%20%7D%20from%20'react'%3B%0Aimport%20%7B%0A%20%20AppRegistry%2C%0A%20%20StyleSheet%2C%0A%20%20Text%2C%0A%20%20View%2C%0A%7D%20from%20'react-native'%3B%0A%0Aclass%20App%20extends%20Component%20%7B%0A%20%20render%28%29%20%7B%0A%20%20%20%20return%20%28%0A%20%20%20%20%20%20%3CView%20style%3D%7Bstyles.container%7D%3E%0A%20%20%20%20%20%20%20%20%3CText%20style%3D%7Bstyles.welcome%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%7Brequire%28'test'%29.getText%28%29%7D%0A%20%20%20%20%20%20%20%20%3C%2FText%3E%0A%20%20%20%20%20%20%3C%2FView%3E%0A%20%20%20%20%29%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20styles%20%3D%20StyleSheet.create%28%7B%0A%20%20container%3A%20%7B%0A%20%20%20%20flex%3A%201%2C%0A%20%20%20%20justifyContent%3A%20'center'%2C%0A%20%20%20%20alignItems%3A%20'center'%2C%0A%20%20%20%20backgroundColor%3A%20'%23F5FCFF'%2C%0A%20%20%7D%2C%0A%20%20welcome%3A%20%7B%0A%20%20%20%20fontSize%3A%2020%2C%0A%20%20%20%20textAlign%3A%20'center'%2C%0A%20%20%20%20margin%3A%2010%2C%0A%20%20%7D%2C%0A%7D%29%3B%0A%0AAppRegistry.registerComponent%28'App'%2C%20%28%29%20%3D%3E%20App%29%3B%0A).

Probably not a big deal though, since people will most likely need to specially bundle their RN modules for the web player anyway. What do you think?

**Comment by nbclark** [comment]
You're more of the expert here, so I'll defer to you. I modeled the vendor components after the way Rect/ReactNative are packaged (and dumped into the window namespace).

My thought on when this would be used was for companies or vendors who build exported libraries/packages that can be compiled for web and then included in the demo player without having to rebundle.

So I think I'm on the same page as you that packaging for the web player seems to make the most sense. But happy to make the change if you like.

**Comment by dabbott** [comment]
Yeah, I think you're right. Let's keep it like this and see if/how people start using it.

**Comment by dabbott** [comment]
Updated readme with runnable example
